server:
  port: 8083
  servlet:
    context-path: /wx

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  data:
    # Redis 配置
    redis:
      host: 8.137.62.188
      port: 10005
      password: cskaoyan
      database: 0
      timeout: 60000
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.137.62.188:10002
    username: cskaoyan
    password: 2wsx#EDC
    # Druid 配置
    druid:
      filter:
        config:
          #开启密钥加密
          enabled: true
        stat:
          enabled: true
      # Druid 数据库连接池 配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      # Druid Web 监控配置
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        allow: "0.0.0.0"
        login-username: cskaoyan
        login-password: 2wsx#EDC
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: "/druid/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
# MyBatis 配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: happy.coding.bean.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
# PageHelper 配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true
# 日志 配置
logging:
  level:
    happy.coding: info
# OpenAPI 配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
  group-configs:
    - group: 'happy.coding'
      paths-to-match: '/**'
      packages-to-scan: happy.coding
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    enable-version: true
    enable-after-script: true
    enable-reload-cache-parameter: true
    enable-request-cache: true
    enable-search: true
    enable-footer: false
    enable-dynamic-parameter: true
    enable-debug: true
    enable-open-api: true
    enable-group: true
  basic:
    enable: true
    username: cskaoyan
    password: 2wsx#EDC
# JWT 配置
jwt:
  cookie-key: X-CskaoyanMarket-Token
  # payload
  subject: USER-AUTH
  audience: MINI-APP
  issuer: CSKAOYAN-MARKET
  expiration-time: 7200 # 7200s = 2h
  custom-id-key: userId
  # signature
  secret-key: cskaoyan-jwt-secret-key-which-size-must-gt-256



