server:
  port: 8083
  servlet:
    context-path: /wx

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: 此处填写url
      username: 此处填写数据库username
      password: 此处填写数据库password
      # Druid 数据库连接池 配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      # Druid Web 监控配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow: "0.0.0.0"
        login-username: 此处填写数据库连接池监控username
        login-password: 此处填写数据库连接池监控password
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
# MyBatis 配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: happy.coding.bean.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
# PageHelper 配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true
# 日志 配置
logging:
  level:
    happy.coding: info
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
  group-configs:
    - group: 'happy.coding'
      paths-to-match: '/**'
      packages-to-scan: happy.coding
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    enable-version: true
    enable-after-script: true
    enable-reload-cache-parameter: true
    enable-request-cache: true
    enable-search: true
    enable-footer: false
    enable-dynamic-parameter: true
    enable-debug: true
    enable-open-api: true
    enable-group: true
  basic:
    enable: true
    username: 此处填写生成文档username
    password: 此处填写生成文档password
